// Copy this from your backend config/skills.js
const AVAILABLE_SKILLS = [
    "Python",
    "JavaScript",
    "Java",
    "C#",
    "C++",
    "HTML",
    "CSS",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "FastAPI",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "Git",
    "GitHub",
    "REST API",
    "GraphQL",
    "UI/UX Design",
    "Figma",
    "Data Analysis",
    "Pandas",
    "NumPy",
    "Power BI",
    "Excel",
    "Machine Learning",
    "Artificial Intelligence"
];

export default AVAILABLE_SKILLS;